# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
  
    continue-on-error: true
    strategy:
      matrix:
        python_minor_version:
          - '7'
          - '8'
          - '9'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Needed for running build scripts
      - name: Setup Python
        uses: actions/setup-python@v2.2.2

      - name: Run Tests trough Docker with Python 3.${{ matrix.python_minor_version }}
        run: cd build/docker && python3 run-tests.py ${{ matrix.python_minor_version }}
